title: U.S. Federal Public Trust TLS Certificate Policy
small_title: U.S. Federal Public Trust TLS PKI
smallest_title: U.S. Federal Public Trust TLS PKI
description: Certificate Policy for a new public key infrastructure for TLS certificates for public .gov and .mil websites.
email: fpki@gsa.gov
author:
    name: FICAM
repo_url: https://github.com/uspki/policies
baseurl: ''
branch: policy-pages
# Federalist overwrites the site.branch value when deploying
# the site.branch was used in dynamic link generation for objects including Edit Page
# we want the dynamic links to send users to the the primary editing branch.  editbranch is the new site variable to ensure Edit Page sends users to the correct branch for pull requests.
editbranch: master

github_info:
  organization: uspki
  repository: policies
  default_branch: master

report_url: "assets/docs/US_Federal_Public_Trust_TLS_Certificate_Policy_v1_0.pdf"

google_analytics_ua:
repo: https://github.com/uspki/policies

dap:
  agency: GSA

primary_navigation:
  - name: Home
    description: Background
    url: /
  - name: Certificate Policy
    url: /certificatepolicy/
  - name: Certificate Profiles
    url: /certificateprofiles/
  - name: Submit Comments
    url: /comment/

secondary_navigation:
  - name: Contact Us
    url: https://www.idmanagement.gov/contact-us/
  - name: About Us
    url: https://www.idmanagement.gov/about-us/
  - name: Contribute
    url: https://www.idmanagement.gov/contribute/

searchgov:

  # You should not change this.
  endpoint: https://search.usa.gov

  # replace this with your search.gov account
  affiliate: idmprod

  # replace with your access key
  access_key: zCEoL5u4U5XFzfFSxy8y4Iz6vdtTjsb4U539L_rgDTM=

  # this renders the results within the page instead of sending to user to search.gov
  inline: false

exclude:
- CONTRIBUTING.md
- _config.yml
- .travis.yml
- .gitignore
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- manifest.yml
- Staticfile
- Staticfile.auth
- Dockerfile
- docker-compose.yml

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "base"

collections:
  pages:
    output: true
    #permalink: /:path/

assets:
  autoprefixer:
    browsers:
      - "> 2%"
      - "last 2 versions"
      - "IE 11"
      - "not dead"
  sources:
    - node_modules/uswds/dist/img
    - node_modules/uswds/dist/js
    - node_modules/uswds/dist/scss
    - node_modules/netlify-cms/dist
